name: Run Tests on Pull Request

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install npm packages
        run: npm ci

      - name: Run Tests
        run: npm run test    